### ISSUE TITLE
make in symbols not working

### ISSUE THREAD

**Issue by travnick** [hughski/colorhug2-hardware#1]
$ cd symbols ; make
make: **\* No targets specified and no makefile found.  Stop.

**Comment by travnick** [comment]
Unfortunately the same error.
I guess more steps are needed, some configure step, automoc or something?

**Comment by hughsie** [comment]
Yes, you need to do ./autogen.sh in the top level directory first.

**Comment by travnick** [comment]
Indeed. Now it works :+1: Are you able to add this step to all your repositories with schematics?
