### ISSUE TITLE
Component [L78L33AC.sym] was not found in the component library

### ISSUE THREAD

**Issue by travnick** [hughski/colorhug2-hardware#2]
When running `gschem hardware.sch` Error appears in log console: `Component [L78L33AC.sym] was not found in the component library`

**Comment by hughsie** [comment]
Did you run make before opening it in gschem?

**Comment by travnick** [comment]
without make I get many more issues about component not found.
Maybe is it caused by your last commit?
https://github.com/hughski/colorhug2-hardware/commit/23abea690000001d2185a189e631225a64cb67c2
